r302 '/bosh/bosh-errands.html', '/bosh/jobs.html'
r302 '/deploying/vsphere/cloud-foundry-example-manifest.html', '/deploying/vsphere/index.html'
r302 '/deploying/vcloud/cloud-foundry-example-manifest.html', '/deploying/vcloud/index.html'
r302 '/devguide/deploy-apps/api-endpoint.html', '/running/cf-api-endpoint.html'
r302 '/console/cf-api-endpoint.html', '/running/cf-api-endpoint.html'
r302 '/devguide/deploy-apps/sts.html', '/buildpacks/java/sts.html'
