---
resources:
- name: book
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-book.git

- name: layout
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-layout.git

- name: cf-concepts
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-cloudfoundry-concepts.git

- name: cf-devguide
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-dev-guide.git

- name: cf-cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-cf-cli.git

- name: cf-admin
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-cf-admin.git

- name: cf-services
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-services.git

- name: cf-running-cf
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-running-cf.git

- name: cf-buildpacks
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-buildpacks.git

- name: apps
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-apps.git

- name: billing
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-billing.git

- name: console
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-console.git

- name: getting-started
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-getting-started.git

- name: service-connector
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-service-connector.git

- name: service-offerings
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-service-offerings.git

- name: tutorial-clojure
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-clojure.git

- name: tutorial-node
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-node.git

- name: tutorial-php
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-php.git

- name: tutorial-python
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-python.git

- name: tutorial-ruby
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-ruby.git

- name: api
  type: git
  source:
    uri: https://github.com/swisscom/docs-api.git

jobs:
- name: deploy
  plan:
  - aggregate:
    - get: book
      trigger: true
    - get: layout
      trigger: true
    - get: cf-concepts
      trigger: true
    - get: cf-devguide
      trigger: true
    - get: cf-cli
      trigger: true
    - get: cf-admin
      trigger: true
    - get: cf-services
      trigger: true
    - get: cf-running-cf
      trigger: true
    - get: cf-buildpacks
      trigger: true
    - get: apps
      trigger: true
    - get: billing
      trigger: true
    - get: console
      trigger: true
    - get: getting-started
      trigger: true
    - get: service-connector
      trigger: true
    - get: service-offerings
      trigger: true
    - get: tutorial-clojure
      trigger: true
    - get: tutorial-node
      trigger: true
    - get: tutorial-php
      trigger: true
    - get: tutorial-python
      trigger: true
    - get: tutorial-ruby
      trigger: true
    - get: api
      trigger: true

  - task: build
    file: book/ci/tasks/build.yml

  - task: deploy
    file: book/ci/tasks/deploy.yml
    params:
      CF_API: {{CF_API}}
      CF_SHARED_DOMAIN: {{CF_SHARED_DOMAIN}}
      CF_USERNAME: {{CF_USERNAME}}
      CF_PASSWORD: {{CF_PASSWORD}}
      CF_ORG: {{CF_ORG}}
      CF_SPACE: {{CF_SPACE}}
