---
resources:
- name: resource-book
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-book.git

- name: resource-layout
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-layout.git

- name: resource-cf-concepts
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-cloudfoundry-concepts.git

- name: resource-cf-devguide
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-dev-guide.git

- name: resource-cf-cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-cf-cli.git

- name: resource-cf-admin
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-cf-admin.git

- name: resource-cf-services
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-services.git

- name: resource-cf-running-cf
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-running-cf.git

- name: resource-cf-buildpacks
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-buildpacks.git

- name: resource-apps
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-apps.git

- name: resource-billing
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-billing.git

- name: resource-console
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-console.git

- name: resource-getting-started
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-getting-started.git

- name: resource-service-connector
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-service-connector.git

- name: resource-service-offerings
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-service-offerings.git

- name: resource-tutorial-clojure
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-clojure.git

- name: resource-tutorial-node
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-node.git

- name: resource-tutorial-php
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-php.git

- name: resource-tutorial-python
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-python.git

- name: resource-tutorial-ruby
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-ruby.git

- name: resource-api
  type: git
  source:
    uri: https://github.com/swisscom/docs-api.git

jobs:
- name: job-deploy
  plan:
  - aggregate:
    - get: resource-book
      trigger: true
    - get: resource-layout
      trigger: true
    - get: resource-cf-concepts
      trigger: true
    - get: resource-cf-devguide
      trigger: true
    - get: resource-cf-cli
      trigger: true
    - get: resource-cf-admin
      trigger: true
    - get: resource-cf-services
      trigger: true
    - get: resource-cf-running-cf
      trigger: true
    - get: resource-cf-buildpacks
      trigger: true
    - get: resource-apps
      trigger: true
    - get: resource-billing
      trigger: true
    - get: resource-console
      trigger: true
    - get: resource-getting-started
      trigger: true
    - get: resource-service-connector
      trigger: true
    - get: resource-service-offerings
      trigger: true
    - get: resource-tutorial-clojure
      trigger: true
    - get: resource-tutorial-node
      trigger: true
    - get: resource-tutorial-php
      trigger: true
    - get: resource-tutorial-python
      trigger: true
    - get: resource-tutorial-ruby
      trigger: true
    - get: resource-api
      trigger: true

  - task: build
    file: resource-book/ci/tasks/build.yml

  - task: deploy
    file: resource-book/ci/tasks/deploy.yml
    params:
      CF_API: {{CF_API}}
      CF_SHARED_DOMAIN: {{CF_SHARED_DOMAIN}}
      CF_USERNAME: {{CF_USERNAME}}
      CF_PASSWORD: {{CF_PASSWORD}}
      CF_ORG: {{CF_ORG}}
      CF_SPACE: {{CF_SPACE}}
