---
groups:
- name: all
  jobs:
  - build
  - bump major
  - bump minor
  - bump patch
  - deploy dev
  - deploy prd
- name: build
  jobs:
  - build
- name: version
  jobs:
  - bump major
  - bump minor
  - bump patch
- name: deploy
  jobs:
  - deploy dev
  - deploy prd

resource_types:
- name: atmos-resource
  type: docker-image
  source:
    repository: docker-registry.service.consul:5000/atmos-resource
- name: git-http-resource
  type: docker-image
  source:
    repository: docker-registry.service.consul:5000/git-resource
- name: semver-git-http-resource
  type: docker-image
  source:
    repository: docker-registry.service.consul:5000/semver-resource

resources:
- name: book
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-book.git

- name: cf-concepts
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-cloudfoundry-concepts.git

- name: cf-devguide
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-dev-guide.git

- name: cf-cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-cf-cli.git

- name: cf-buildpacks
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-buildpacks.git

- name: devguide
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-devguide.git

- name: billing
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-billing.git

- name: console
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-console.git

- name: getting-started
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-getting-started.git

- name: service-connector
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-service-connector.git

- name: service-offerings
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-service-offerings.git

- name: tutorial-clojure
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-clojure.git

- name: tutorial-go
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-go.git

- name: tutorial-java
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-java.git

- name: tutorial-node
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-node.git

- name: tutorial-php
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-php.git

- name: tutorial-python
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-python.git

- name: tutorial-ruby
  type: git
  source:
    uri: https://github.com/swisscom/docs-appcloud-tutorial-ruby.git

- name: api
  type: git
  source:
    uri: https://github.com/swisscom/docs-api.git

- name: concourse-utils
  type: git-http-resource
  check_every: 10m
  source:
    uri: https://gitlab.swisscloud.io/appc-cf-core/concourse-utils.git
    branch: master
    username: {{GITLAB_USER}}
    password: {{GITLAB_PASSWORD}}

- name: docs-version
  type: semver-git-http-resource
  check_every: 10m
  source:
    initial_version: 1.10.0
    driver: git
    uri: https://gitlab.swisscloud.io/appc-cf-core/ci_semver.git
    branch: docs-release
    file: version
    username: {{GITLAB_USER}}
    password: {{GITLAB_PASSWORD}}

- name: docs-release
  type: atmos-resource
  source:
    endpoint: ds31s3.swisscom.com
    bucket: docs-releases
    private: true
    regexp: docs-([0-9\.]+).tgz
    access_key: {{S3_ACCESS_KEY}}
    secret_key: {{S3_SECRET_KEY}}

jobs:
- name: build
  serial_groups: [version]
  build_logs_to_retain: 100
  plan:
  - do:
    - aggregate:
      - get: book
        trigger: true
      - get: cf-concepts
        trigger: true
      - get: cf-devguide
        trigger: true
      - get: cf-cli
        trigger: true
      - get: cf-buildpacks
        trigger: true
      - get: devguide
        trigger: true
      - get: billing
        trigger: true
      - get: console
        trigger: true
      - get: getting-started
        trigger: true
      - get: service-connector
        trigger: true
      - get: service-offerings
        trigger: true
      - get: tutorial-clojure
        trigger: true
      - get: tutorial-go
        trigger: true
      - get: tutorial-java
        trigger: true
      - get: tutorial-node
        trigger: true
      - get: tutorial-php
        trigger: true
      - get: tutorial-python
        trigger: true
      - get: tutorial-ruby
        trigger: true
      - get: api
        trigger: true
      - get: docs-version
        params:
          bump: minor
      - get: concourse-utils

    - task: build
      file: book/ci/tasks/build.yml

    - put: docs-release
      params:
        file: final-app/docs-*

    - put: docs-version
      params:
        file: docs-version/version

    on_failure:
      task: slack-notification
      file: book/ci/tasks/slack_error_alert.yml
      params:
        SLACK_MESSAGE: '*docs-dev-release*: building docs failed'

- name: deploy dev
  build_logs_to_retain: 100
  plan:
  - do:
    - aggregate:
      - get: book
      - get: docs-release
        trigger: true
      - get: concourse-utils

    - task: deploy-dev
      file: book/ci/tasks/deploy.dev.yml
      params:
        CF_API: {{CF_API}}
        CF_SHARED_DOMAIN: {{CF_SHARED_DOMAIN}}
        CF_USERNAME: {{CF_USERNAME}}
        CF_PASSWORD: {{CF_PASSWORD}}
        CF_ORG: {{CF_ORG}}
        CF_SPACE: {{CF_SPACE}}

    on_failure:
      task: slack-notification
      file: book/ci/tasks/slack_error_alert.yml
      params:
        SLACK_MESSAGE: '*docs-dev-release*: deploying docs to develop failed'

- name: deploy prd
  build_logs_to_retain: 100
  plan:
  - do:
    - aggregate:
      - get: book
      - get: docs-release
      - get: concourse-utils

    - task: deploy-prd
      file: book/ci/tasks/deploy.prd.yml
      params:
        CF_API: {{CF_API}}
        CF_SHARED_DOMAIN: {{CF_SHARED_DOMAIN}}
        CF_USERNAME: {{CF_USERNAME_PRD}}
        CF_PASSWORD: {{CF_PASSWORD_PRD}}
        CF_ORG: {{CF_ORG}}
        CF_SPACE: {{CF_SPACE_PRD}}

    on_failure:
      task: slack-notification
      file: book/ci/tasks/slack_error_alert.yml
      params:
        SLACK_MESSAGE: '*docs-prd-release*: deploying docs to production failed'

- name: bump major
  serial_groups: [version]
  public: false
  build_logs_to_retain: 50
  plan:
  - get: docs-version
    params:
      bump: major
  - put: docs-version
    params:
      file: docs-version/version

- name: bump minor
  serial_groups: [version]
  public: false
  build_logs_to_retain: 50
  plan:
  - get: docs-version
    params:
      bump: minor
  - put: docs-version
    params:
      file: docs-version/version

- name: bump patch
  serial_groups: [version]
  public: false
  build_logs_to_retain: 50
  plan:
  - get: docs-version
    params:
      bump: patch
  - put: docs-version
    params:
      file: docs-version/version
